- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requiresNda: Command # Funky
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      #time: 2.5h
      time: 10h # Funky
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      #time: 5h
      time: 10h # Funky
    - !type:DepartmentTimeRequirement
      department: Medical
      #time: 10h
      time: 20h # Funky
    - !type:OverallPlaytimeRequirement
      time: 25h # Funky
  #weight: 10 # Funky - Weighting all jobs equally now
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  joinNotifyCrew: true # Funky
  supervisors: job-supervisors-captain
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  special:
  #- !type:AddImplantSpecial
  #  implants: [ MindShieldImplant ] # Funky - Removed mindshields
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    back: ClothingBackpackSatchelLeather # funky
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: ChiefMedicalOfficerChameleonOutfit
  job: ChiefMedicalOfficer
  hasMindShield: true
  equipment:
    head: FuClothingHeadHatScrubcapTeal # ClothingHeadHatBeretCmo funky - fuck department berets
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
