- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      #time: 2.5h
      time: 4h # Funky
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

- type: startingGear
  id: DoctorGear
  equipment:
    id: MedicalWallet # Funky: the wallet-ening, also removing the loadout choice for senior stuff
    ears: ClothingHeadsetMedical
    pocket2: PouchMedical # funky

- type: chameleonOutfit
  id: MedicalDoctorChameleonOutfit
  job: MedicalDoctor
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
