- type: job
  id: Magistrate
  name: job-name-magistrate
  description: job-description-magistrate
  playTimeTracker: JobMagistrate
  requirements:
  - !type:RoleTimeRequirement
    role: JobIAA
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 5h

  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  supervisors: job-supervisors-xo
  access:
  - Magistrate
  - Brig
  - InternalAffairs
  - Maintenance

- type: startingGear
  id: MagistrateGear
  equipment:
    head: ClothingHeadHatPwig
    shoes: ClothingShoesBootsLaceup
    id: MagistrateWallet
    ears: ClothingHeadsetMagistrate
    outerClothing: ClothingOuterRobesJudge
    pocket2: PouchGeneric
  storage:
    back:
    - BookSentencingGuidelines

- type: chameleonOutfit
  id: MagistrateChameleonOutfit
  job: Magistrate
  equipment:
    mask: ClothingMaskNeckGaiter
    neck: ClothingNeckScarfStripedPurple
