- type: job
  id: CorporateLiaison
  name: job-name-cl
  description: job-description-cl
  playTimeTracker: JobCorporateLiaison
  requiresNda: Command # Funky
  requirements:
  - !type:DepartmentTimeRequirement
    department: Command
    time: 10h
  - !type:DepartmentTimeRequirement
    department: InternalAffairs
    time: 10h
  startingGear: CLGear
  icon: "JobIconCorporateLiaison"
  supervisors: job-supervisors-centcomm-advisor
  access:
  - Corporate
  - Command
  - Maintenance

- type: startingGear
  id: CLGear
  equipment:
    head: ClothingHeadHatBeretCommand
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    id: CLPDA
    ears: ClothingHeadsetCL
    back: ClothingBackpackSatchelLeather

- type: chameleonOutfit
  id: CLChameleonOutfit
  job: CorporateLiaison
  hasMindShield: true
  equipment:
    mask: ClothingMaskNeckGaiter
    neck: ClothingNeckScarfStripedBlue
    outerClothing: ClothingOuterWinterColorBlue
