- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requiresNda: Command # Funky
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      #time: 4h
      time: 5h # Funky
    - !type:DepartmentTimeRequirement
      department: Medical
      #time: 4h
      time: 5h # Funky
    - !type:DepartmentTimeRequirement
      department: Science
      #time: 4h
      time: 5h # Funky
    - !type:DepartmentTimeRequirement
      department: Security
      #time: 4h
      time: 5h # Funky
    - !type:DepartmentTimeRequirement
      department: InternalAffairs # Funky
      time: 10h
    - !type:DepartmentTimeRequirement
      department: Cargo # Funky
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Service # Funky
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Command
      #time: 4h
      time: 20h # Funky
  #weight: 20 # Funky - Weighting all jobs equally now
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  special:
  #- !type:AddImplantSpecial
  #  implants: [ MindShieldImplant ] # Funky - Removed mindshields
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
    back: ClothingBackpackSatchelCaptain # funky
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
