- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requiresNda: Security # Funky
  requirements:
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 5h
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-commandant #funky
  access:
  - Security
  - Brig
  - Maintenance
  - Detective
  - Cryogenics
  - External
  #special:
  #- !type:AddImplantSpecial
  #  implants: [ MindShieldImplant ] # Funky - Removed mindshields

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectiveWallet # Funky: the wallet-ening
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
    back: ClothingBackpackSatchelLeather # funky
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner

- type: chameleonOutfit
  id: DetectiveChameleonOutfit
  job: Detective
  hasMindShield: true
  equipment:
    head: ClothingHeadHatFedoraBrown
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckTieDet
    gloves: ClothingHandsGlovesForensic
