using Content.Client._Funkystation.SISTRTerminal.Sheetlets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.SISTRTerminal.Programs;

[GenerateTypedNameReferences]
public sealed partial class SistrCommandLine : BoxContainer
{
    public Action<string[]>? RunProgram;

    private static readonly Color PrimaryTextColor = SistrTerminalSheetlet.PrimaryForegroundColor;

    private readonly Dictionary<string, CommandEntry> _commands = new ();

    public SistrCommandLine()
    {
        RobustXamlLoader.Load(this);

        TerminalLineInput.OnTextEntered += args =>
        {
            TerminalLineInput.Clear();
            AddLine($"> {args.Text}");
            ParseCommandInput(args.Text);
        };

        // todo: better way of defining commands?
        AddCommand("clear", Loc.GetString("sistr-terminal-clear-command-description"), ClearTerminalCommand);
        AddCommand("echo", Loc.GetString("sistr-terminal-echo-command-description"), EchoCommand);
        AddCommand("help", Loc.GetString("sistr-terminal-help-command-description"), HelpCommand);
    }

    private void ParseCommandInput(string commandInput)
    {
        if (string.IsNullOrWhiteSpace(commandInput))
        {
            AddLine(Loc.GetString("sistr-terminal-invalid-command"));
            return;
        }

        var arguments = commandInput.Split(' ');
        if (!_commands.TryGetValue(arguments[0], out var command))
            AddLine(Loc.GetString("sistr-terminal-invalid-command"));
        else
            command.Action.Invoke(arguments);
    }

    public void AddCommand(string command, string description, Action<string[]> action)
    {
        _commands.Add(command, new CommandEntry(description, action));
    }

    public void RegisterProgram(string program, string description)
    {
        AddCommand(program, description, RunProgramCommand);
    }

    public void AddLine(string message)
    {
        AddLineFormatted(FormattedMessage.FromUnformatted(message));
    }

    public void AddLineFormatted(FormattedMessage message)
    {
        TerminalOutput.AddMessage(message, PrimaryTextColor);
    }

    public void FocusInput()
    {
        TerminalLineInput.GrabKeyboardFocus();
    }

    private void HelpCommand(string[] args)
    {
        if (args.Length <= 1)
        {
            AddLine(Loc.GetString("sistr-terminal-help-command-start")+"\n");
            foreach (var command in _commands)
            {
                AddLine(Loc.GetString("sistr-terminal-help-command-wrap",
                    ("name", command.Key),
                    ("description", command.Value.Description)));
            }
        }
        else if (_commands.TryGetValue(args[1].ToLower(), out var command))
        {
            AddLine(Loc.GetString("sistr-terminal-help-command-wrap",
                ("name", args[1].ToLower()),
                ("description", command.Description)));
        }
        else
        {
            AddLine(Loc.GetString("sistr-terminal-invalid-command"));
        }
    }

    private void RunProgramCommand(string[] args)
    {
        RunProgram?.Invoke(args);
    }

    private void ClearTerminalCommand(string[] args)
    {
        TerminalOutput.Clear();
    }

    private void EchoCommand(string[] args)
    {
        var input = string.Join(' ', args[1..]);
        AddLine(input);
    }

    private struct CommandEntry(string description, Action<string[]> action)
    {
        public readonly string Description = description;
        public readonly Action<string[]> Action = action;
    }
}
