using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.SISTRTerminal.Programs;

[GenerateTypedNameReferences]
public sealed partial class SistrCommandLine : BoxContainer
{
    public Action<string[]>? RunProgram;

    // todo: better way of defining commands
    private readonly Dictionary<string, Action<string[]>> _commands = new ();

    public SistrCommandLine()
    {
        RobustXamlLoader.Load(this);

        TerminalLineInput.OnTextEntered += args =>
        {
            TerminalLineInput.Clear();
            AddLine($"> {args.Text}");
            ParseCommand(args.Text);
        };

        // todo: better way of defining commands?
        AddCommand("clear", ClearTerminalCommand);
        AddCommand("echo", EchoCommand);
    }

    private void ParseCommand(string command)
    {
        var arguments = command.Split(' ');
        if (!_commands.TryGetValue(arguments[0], out var action))
            AddLine("No such command or program exists.");
        else
            action.Invoke(arguments);
    }

    private void RunProgramCommand(string[] args)
    {
        RunProgram?.Invoke(args);
    }

    private void ClearTerminalCommand(string[] args)
    {
        TerminalOutput.Clear();
    }

    private void EchoCommand(string[] args)
    {
        var input = string.Join(' ', args[1..]);
        AddLine(input);
    }

    public void AddCommand(string command, Action<string[]> action)
    {
        _commands.Add(command, action);
    }

    public void RegisterProgram(string program)
    {
        AddCommand(program, RunProgramCommand);
    }

    public void AddLine(string message)
    {
        AddLineFormatted(FormattedMessage.FromUnformatted(message));
    }

    public void AddLineFormatted(FormattedMessage message)
    {
        TerminalOutput.AddMessage(message);
    }

    public void FocusInput()
    {
        TerminalLineInput.GrabKeyboardFocus();
    }
}
