using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.SISTRTerminal.Programs;

[GenerateTypedNameReferences]
public sealed partial class SistrBinaryChat : SistrProgram
{
    public Action<string>? SendMessage;

    public SistrBinaryChat()
    {
        RobustXamlLoader.Load(this);

        ChatInput.OnTextEntered += input =>
        {
            ChatInput.Clear();
            ParseInput(input.Text);
        };
    }

    private void ParseInput(string input)
    {
        if (string.IsNullOrEmpty(input))
            return;

        if (input.StartsWith("/exit"))
        {
            Exit();
            return;
        }

        SendMessage?.Invoke(input);
    }

    public void Update<T>(T messages) where T : IEnumerable<string>
    {
        ChatLog.Clear();
        foreach (var message in messages)
        {
            ChatLog.AddText(message);
        }
    }

    private void Exit()
    {
        ExitProgram?.Invoke(this);
    }
}
