- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requiresNda: Command # Funky
  requirements:
    #- !type:RoleTimeRequirement
    #  role: JobAtmosphericTechnician
    #  time: 2.5h # Funky
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      #time: 5h
      time: 10h # Funky
    - !type:DepartmentTimeRequirement
      department: Engineering
      #time: 10h
      time: 20h # Funky
    - !type:OverallPlaytimeRequirement
      time: 25h # Funky
  #weight: 10 # Funky - Weighting all jobs equally now
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  joinNotifyCrew: true # Funky
  supervisors: job-supervisors-captain
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  special:
  #- !type:AddImplantSpecial
  #  implants: [ MindShieldImplant ] # Funky - Removed mindshields
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    id: CEPDA
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    belt: ClothingBeltUtilityEngineering
    back: ClothingBackpackSatchelLeather # funky
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: ChiefEngineerChameleonOutfit
  job: ChiefEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretEngineering
    mask: ClothingMaskBreath
    neck: ClothingNeckCloakCe
    outerClothing: ClothingOuterWinterCE
    gloves: FuClothingHandsGlovesInsuls #Funky
    shoes: ClothingShoesBootsMagAdv
