- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requiresNda: Command # Funky
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 5h
    - !type:RoleTimeRequirement
      role: JobBotanist #funky - replaces salvage
      time: 2.5h
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10h
    - !type:OverallPlaytimeRequirement
      time: 20h # Funky
  #weight: 10 # Funky - Weighting all jobs equally now
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  joinNotifyCrew: true # Funky
  supervisors: job-supervisors-captain
  access:
  - Cargo
  - Hydroponics # Funky - Botanist is now in Logistics
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  #- !type:AddImplantSpecial
  #  implants: [ MindShieldImplant ] # Funky - Removed mindshields
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboardThreePapers
    pocket1: AppraisalTool
    back: ClothingBackpackSatchelLeather # funky
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: QuartermasterChameleonOutfit
  job: Quartermaster
  hasMindShield: true
  equipment:
    head: ClothingHeadHatQMsoft
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterQM
    neck: ClothingNeckCloakQm
    gloves: ClothingHandsKnuckleDustersQM
