using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.SISTRTerminal.Programs.MassScanner;

[GenerateTypedNameReferences]
public sealed partial class SistrMassScanner : SistrProgramControl
{
    public void UpdateState(NavInterfaceState scc)
    {
        RadarScreen.UpdateState(scc);
    }

    public SistrMassScanner()
    {
        RobustXamlLoader.Load(this);
        LineInput.OnTextEntered += args =>
        {
            if (args.Text == "exit")
                ExitProgram?.Invoke();
        };
    }
}
