using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;

namespace Content.Client._Funkystation.SISTRTerminal.Programs.MassScanner;

[GenerateTypedNameReferences]
public sealed partial class SistrMassScanner : SistrProgramControl
{
    public void UpdateState(NavInterfaceState scc)
    {
        RadarScreen.UpdateState(scc);
    }
}
