using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.SISTRTerminal;

[GenerateTypedNameReferences]
public sealed partial class SistrTerminalUi : FancyWindow
{
    public Action<string>? CommandEntered;

    public SistrTerminalUi()
    {
        RobustXamlLoader.Load(this);

        TerminalLineInput.OnTextEntered += args => CommandEntered?.Invoke(args.Text);
    }

    public void AddLine(string s)
    {
        TerminalOutput.AddMessage(FormattedMessage.FromUnformatted(s));
    }
}
