using Content.Client._Funkystation.SISTRTerminal.Programs;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Sandboxing;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.SISTRTerminal;

[GenerateTypedNameReferences]
public sealed partial class SistrTerminalUi : FancyWindow
{
    [Dependency] private ISandboxHelper _sandboxHelper = null!;
    private Dictionary<string, Action> _programs = new();
    public string CurrentProgram { get; private set; }

    public SistrTerminalUi()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _programs.Add("binarychat", RunProgram<SistrCommandLine>);

        CurrentProgram = "CommandLine";
        SistrCommandLine.RunProgram += HandleRunProgram;
    }

    private void HandleRunProgram(string[] args)
    {
        if (_programs.TryGetValue(args[0], out var program))
        {
            CurrentProgram = args[0];
            program.Invoke();
        }
    }

    private void HandleExitProgram<T>(T program) where T : SistrProgram
    {
        program.Orphan();
        SistrCommandLine.Visible = true;
        CurrentProgram = "CommandLine";
    }

    private void RunProgram<T>() where T : SistrProgram, new()
    {
        SistrCommandLine.Visible = false;
        var program = _sandboxHelper.CreateInstance(typeof(T)) as T;
        AddChild(program!);
        program!.ExitProgram += HandleExitProgram;
    }
}

public abstract class SistrProgram : BoxContainer
{
    public Action<SistrProgram>? ExitProgram;
}
