using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.SISTRTerminal;

[GenerateTypedNameReferences]
public sealed partial class SistrTerminalUi : FancyWindow
{
    public SistrTerminalUi()
    {
        RobustXamlLoader.Load(this);
    }

    public void OpenProgram(ref SistrProgramControl program)
    {
        SistrCommandLine.Visible = false;
        InternalWindow.AddChild(program);
    }

    public void OnProgramClosed()
    {
        SistrCommandLine.Visible = true;
    }
}

public abstract class SistrProgramControl : BoxContainer
{
    public Action? ExitProgram;

    protected virtual void Exit()
    {
        ExitProgram?.Invoke();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        Exit();
    }
}
