- type: job
  id: Passenger
  name: job-name-assistant
  description: job-description-assistant
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerWallet # Funky: the wallet-ening
    ears: ClothingHeadsetGrey
    pocket2: PouchGeneric # funky
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: FuClothingHandsGlovesInsulsBudget #Funky
