- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  #requirements:
  #  - !type:DepartmentTimeRequirement
  #    department: Civilian # Funky - Service is now a separate department
  #    time: 0.5h # Funky - Removing role timer for parity
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hd # funky
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  #- Hydroponics # Funky - Botanist is now in Logistics
  - Bar

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesChef
    id: ChefWallet # Funky: the wallet-ening
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
    pocket2: PouchGeneric # funky
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ChefChameleonOutfit
  job: Chef
  equipment:
    head: ClothingHeadHatChef
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskItalianMoustache
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterJacketChef
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesChef
