- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  startingGear: JanitorGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hd # funky
  access:
  - Service
  - Janitor
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: JanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorWallet # Funky: the wallet-ening
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
    pocket2: PouchGeneric # funky

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    id: JanitorWallet # Funky: the wallet-ening
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled

- type: chameleonOutfit
  id: JanitorChameleonOutfit
  job: Janitor
  equipment:
    head: ClothingHeadHatPurplesoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterWinterJani
    gloves: ClothingHandsGlovesJanitor
