- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  requirements:
  #- !type:DepartmentTimeRequirement
  #  department: Civilian # Funky - Service is now a separate department
  #  time: 0.5h # Funky - Removed role timer for parity
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-hd # funky
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  #extendedAccess: # Funky - Botanist is now in Logistics
  #- Hydroponics

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerWallet # Funky: the wallet-ening
    ears: ClothingHeadsetService
    pocket2: PouchGeneric # funky
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ServiceWorkerChameleonOutfit
  job: ServiceWorker
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterVest
    gloves: ClothingHandsGlovesColorBlack
