- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      #time: 10h
      time: 35h
      inverted: true # stop playing intern if you're good at science!
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantWallet # Funky: the wallet-ening
    ears: ClothingHeadsetScience
    pocket1: BookScientistsGuidebook # funky, pocket1
    pocket2: PouchResearch # funky
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ResearchAssistantChameleonOutfit
  job: ResearchAssistant
  equipment:
    head: ClothingHeadHatCardborg
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
