using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.SISTRTerminal.Programs.AutomaTalk;

[GenerateTypedNameReferences]
public sealed partial class SistrAutomaTalk : SistrProgramControl
{
    public Action<string>? SendMessage;
    [Dependency] private ILogManager _logManager = null!;
    private ISawmill _sawmill;

    public SistrAutomaTalk()
    {
        RobustXamlLoader.Load(this);

        ChatInput.OnTextEntered += input =>
        {
            ChatInput.Clear();
            ParseInput(input.Text);
        };

        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("automatalk");
    }

    private void ParseInput(string input)
    {
        if (string.IsNullOrEmpty(input))
            return;

        if (input.StartsWith("/exit"))
        {
            Exit();
            return;
        }

        SendMessage?.Invoke(input);
    }

    public void Update<T>(T messages) where T : IEnumerable<string>
    {
        ChatLog.Clear();
        foreach (var message in messages)
        {
            ChatLog.AddText(message);
        }
    }

    private void Exit()
    {
        ExitProgram?.Invoke();
    }
}
