using Content.Shared._Funkystation.SISTR;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Funkystation.SISTRTerminal.Programs.AutomaTalk;

[GenerateTypedNameReferences]
public sealed partial class SistrAutomaTalk : SistrProgramControl
{
    public Action<string>? SendMessage;
    private const string ExitCommand = "/exit";

    private static readonly FormattedMessage EndOfLogMessage =
        FormattedMessage.FromUnformatted(
            Loc.GetString("automatalk-end-of-messages"));

    public SistrAutomaTalk()
    {
        RobustXamlLoader.Load(this);

        ChatInput.OnTextEntered += input =>
        {
            ChatInput.Clear();
            ParseInput(input.Text);
        };
    }

    private void ParseInput(string input)
    {
        if (string.IsNullOrEmpty(input))
            return;

        if (input.StartsWith(ExitCommand))
        {
            Exit();
            return;
        }

        SendMessage?.Invoke(input);
    }

    public void RefreshChatLog<T>(T messages) where T : IEnumerable<string>
    {
        ChatLog.Clear();
        ChatLog.AddMessage(EndOfLogMessage);
        foreach (var message in messages)
        {
            AddText(message);
        }
    }

    public void UpdateOnMessageReceived(string message)
    {
        if (ChatLog.EntryCount >= SharedSistrCoreSystem.AutomaTalkHistoryLength)
        {
            while (ChatLog.EntryCount > SharedSistrCoreSystem.AutomaTalkHistoryLength)
            {
                ChatLog.RemoveEntry(0);
            }
            ChatLog.SetMessage(0, EndOfLogMessage);
        }
        AddText(message);
    }

    public void FocusInput()
    {
        ChatInput.GrabKeyboardFocus();
    }

    public void AddText(string message)
    {
        ChatLog.AddText(message);
    }
}
