using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.SISTRTerminal.Programs.AutomaTalk;

[GenerateTypedNameReferences]
public sealed partial class SistrAutomaTalk : SistrProgramControl
{
    public Action<string>? SendMessage;
    private const string ExitCommand = "/exit";

    public SistrAutomaTalk()
    {
        RobustXamlLoader.Load(this);

        ChatInput.OnTextEntered += input =>
        {
            ChatInput.Clear();
            ParseInput(input.Text);
        };
    }

    private void ParseInput(string input)
    {
        if (string.IsNullOrEmpty(input))
            return;

        if (input.StartsWith(ExitCommand))
        {
            Exit();
            return;
        }

        SendMessage?.Invoke(input);
    }

    // todo: maybe update the chat log in a better way than just resetting it every time
    public void Update<T>(T messages) where T : IEnumerable<string>
    {
        ChatLog.Clear();
        foreach (var message in messages)
        {
            ChatLog.AddText(message);
        }
    }

    public void FocusInput()
    {
        ChatInput.GrabKeyboardFocus();
    }

    public void AddLine(string message)
    {
        ChatLog.AddText(message);
    }
}
